# Generated by Django 3.0.3 on 2020-11-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rater_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
